// src/views/attributes/UnratedAttribute.svelte
<script lang="ts">
	// Types/constants
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'


	// Props
	const {
		wallet,
	}: {
		wallet: RatedWallet<string>
	} = $props()

	const githubUrl = $derived(
		wallet.types.SOFTWARE ?
			`https://github.com/walletbeat/walletbeat/tree/beta/data/software-wallets/${wallet.metadata.id}.ts`
		: wallet.types.HARDWARE ?
			`https://github.com/walletbeat/walletbeat/tree/beta/data/hardware-wallets/${wallet.metadata.id}.ts`
		: wallet.types.EMBEDDED ?
			`https://github.com/walletbeat/walletbeat/tree/beta/data/embedded-wallets/${wallet.metadata.id}.ts`
		:
			''
	)


	// Components
	import Typography from '@/components/Typography.svelte'
</script>


<Typography
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: `Walletbeat's database does not have the necessary information on **{{WALLET_NAME}}** to assess this question. Please help us by contributing your knowledge on our [GitHub repository](${githubUrl})!`
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

// src/ui/molecules/attributes/UnratedAttribute.tsx
import { Typography } from '@mui/material';

import { Rating, type Value } from '@/schema/attributes';
import type { UnratedAttributeProps } from '@/types/content/unrated-attribute';

import { ExternalLink } from '../../atoms/ExternalLink';
import { WrapRatingIcon } from '../../atoms/WrapRatingIcon';

export function UnratedAttribute<V extends Value>({
	wallet,
}: UnratedAttributeProps<V>): React.JSX.Element {
	return (
		<WrapRatingIcon rating={Rating.UNRATED}>
			<Typography>
				Walletbeat&apos;s database does not have the necessary information on{' '}
				{wallet.metadata.displayName} to assess this question.
			</Typography>
			<Typography>
				Please help us by contributing your knowledge on{' '}
				<ExternalLink url='https://github.com/walletbeat/walletbeat' rel=''>
					our repository
				</ExternalLink>
				!
			</Typography>
		</WrapRatingIcon>
	);
}
