// src/ui/molecules/attributes/UnratedAttribute.tsx
import { Typography } from '@mui/material';

import { Rating, type Value } from '@/schema/attributes';
import type { UnratedAttributeProps } from '@/types/content/unrated-attribute';

import { ExternalLink } from '../../atoms/ExternalLink';
import { WrapRatingIcon } from '../../atoms/WrapRatingIcon';

export function UnratedAttribute<V extends Value>({
	wallet,
}: UnratedAttributeProps<V>): React.JSX.Element {
	return (
		<WrapRatingIcon rating={Rating.UNRATED}>
			<Typography>
				Walletbeat&apos;s database does not have the necessary information on{' '}
				{wallet.metadata.displayName} to assess this question.
			</Typography>
			<Typography>
				Please help us by contributing your knowledge on{' '}
				<ExternalLink url='https://github.com/walletbeat/walletbeat' rel=''>
					our repository
				</ExternalLink>
				!
			</Typography>
		</WrapRatingIcon>
	);
}

// src/ui/molecules/attributes/UnratedAttribute.svelte
<script lang="ts">
	// Types/constants
	import type { Value } from '@/schema/attributes'
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'


	// Props
	let {
		wallet,
		value,
	}: {
		wallet: RatedWallet
		value: Value
	} = $props()


	// Components
	import Typography from '@/ui/atoms/Typography.svelte'
</script>


<Typography
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: `Walletbeat's database does not have the necessary information on **{{WALLET_NAME}}** to assess this question.

Please help us by contributing your knowledge on our repository!`
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

<a href="https://github.com/walletbeat/walletbeat" target="_blank" rel="noopener noreferrer" class="repo-link">
	GitHub Repository
</a>

<style>
	.repo-link {
		margin-top: 0.5rem;
		display: inline-block;
	}
</style>
