// src/ui/atoms/RenderCustomContent.tsx
import { type CustomContent } from '@/types/content'
import { AddressCorrelationDetails } from '@/ui/molecules/attributes/privacy/AddressCorrelationDetails'
import { ChainVerificationDetails } from '@/ui/molecules/attributes/security/ChainVerificationDetails'
import { ScamAlertDetails } from '@/ui/molecules/attributes/security/ScamAlertDetails'
import { SecurityAuditsDetails } from '@/ui/molecules/attributes/security/SecurityAuditsDetails'
import { TransactionInclusionDetails } from '@/ui/molecules/attributes/self-sovereignty/TransactionInclusionDetails'
import { FundingDetails } from '@/ui/molecules/attributes/transparency/FundingDetails'
import { LicenseDetails } from '@/ui/molecules/attributes/transparency/LicenseDetails'
import { SourceVisibilityDetails } from '@/ui/molecules/attributes/transparency/SourceVisibilityDetails'
import { UnratedAttribute } from '@/ui/molecules/attributes/UnratedAttribute'

export function RenderCustomContent<
	CustomContent_ extends CustomContent,
>({
	content,
	...otherProps
}: {
	content: CustomContent_,
} & CustomContent_['component']['componentProps']) {
	const { component, componentProps } = content.component

	switch (component) {
		case 'AddressCorrelationDetails':
			return <AddressCorrelationDetails {...componentProps} {...otherProps} />
		case 'ChainVerificationDetails':
			return <ChainVerificationDetails {...componentProps} {...otherProps} />
		case 'FundingDetails':
			return <FundingDetails {...componentProps} {...otherProps} />
		case 'LicenseDetails':
			return <LicenseDetails {...componentProps} {...otherProps} />
		case 'ScamAlertDetails':
			return <ScamAlertDetails {...componentProps} {...otherProps} />
		case 'SecurityAuditsDetails':
			return <SecurityAuditsDetails {...componentProps} {...otherProps} />
		case 'SourceVisibilityDetails':
			return <SourceVisibilityDetails {...componentProps} {...otherProps} />
		case 'TransactionInclusionDetails':
			return <TransactionInclusionDetails {...componentProps} {...otherProps} />
		case 'UnratedAttribute':
			return <UnratedAttribute {...componentProps} {...otherProps} />
	}
}

// src/ui/atoms/RenderCustomContent.svelte
<script
	lang="ts"
	generics="CustomContent extends _CustomContent"
>
	// Types/constants
	import type { CustomContent as _CustomContent } from '@/types/content'


	// Props
	let {
		content,
		...otherProps
	}: {
		content: CustomContent
	} & CustomContent['component']['componentProps'] = $props()

	const { component: componentName, componentProps } = content.component


	// Components
	import AddressCorrelationDetails from '../molecules/attributes/privacy/AddressCorrelationDetails.svelte'
	import ChainVerificationDetails from '../molecules/attributes/security/ChainVerificationDetails.svelte'
	import ScamAlertDetails from '../molecules/attributes/security/ScamAlertDetails.svelte'
	import SecurityAuditsDetails from '../molecules/attributes/security/SecurityAuditsDetails.svelte'
	import TransactionInclusionDetails from '../molecules/attributes/self-sovereignty/TransactionInclusionDetails.svelte'
	import FundingDetails from '../molecules/attributes/transparency/FundingDetails.svelte'
	import LicenseDetails from '../molecules/attributes/transparency/LicenseDetails.svelte'
	import SourceVisibilityDetails from '../molecules/attributes/transparency/SourceVisibilityDetails.svelte'
	import UnratedAttribute from '../molecules/attributes/UnratedAttribute.svelte'
</script>


{#if componentName === 'AddressCorrelationDetails'}
	<AddressCorrelationDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'ChainVerificationDetails'}
	<ChainVerificationDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'ScamAlertDetails'}
	<ScamAlertDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'SecurityAuditsDetails'}
	<SecurityAuditsDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'TransactionInclusionDetails'}
	<TransactionInclusionDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'FundingDetails'}
	<FundingDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'LicenseDetails'}
	<LicenseDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'SourceVisibilityDetails'}
	<SourceVisibilityDetails
		{...componentProps}
		{...otherProps}
	/>
{:else if componentName === 'UnratedAttribute'}
	<UnratedAttribute
		{...componentProps}
		{...otherProps}
	/>
{/if}
