// src/ui/organisms/Eip7702Table.tsx
import {
	type CellContext,
	type ColumnDef,
	createColumnHelper,
	flexRender,
	getCoreRowModel,
	useReactTable,
} from '@tanstack/react-table'
import React from 'react'

import { eip7702 } from '@/data/eips/eip-7702'
import { erc4337 } from '@/data/eips/erc-4337'
import { ratedSoftwareWallets } from '@/data/software-wallets'
import type { EVMAddress, SmartWalletContract } from '@/schema/contracts'
import { AccountType, isAccountTypeSupported } from '@/schema/features/account-support'
import { refs } from '@/schema/reference'
import { isLabeledUrl } from '@/schema/url'
import { getVariants, type Variant } from '@/schema/variants'
import {
	getVariantResolvedWallet,
	type RatedWallet,
	walletSupportedAccountTypes,
} from '@/schema/wallet'
import { isNonEmptyArray, nonEmptyGet, setContains, setItems } from '@/types/utils/non-empty'
import { cx } from '@/utils/cx'

import { ExternalLink } from '../atoms/ExternalLink'
import { EipStandardTag, walletNameCell } from './WalletTable'

enum WalletTypeFor7702 {
	EIP7702 = 'EIP7702',
	NON_7702_SMART_WALLET = 'NON_7702_SMART_WALLET',
	NON_7702_EOA = 'NON_7702_EOA',
	OTHER = 'OTHER',
}

// TableRow interface for better type safety
interface TableRow {
	id: string
	name: string
	wallet: RatedWallet
	typeFor7702: WalletTypeFor7702
	contract: SmartWalletContract | 'UNKNOWN' | 'NONE'
	sortPriority: number
}

function walletContractUrl(contractAddress: EVMAddress, anchor?: string): string {
	return (
		`https://etherscan.io/address/${contractAddress}` +
		(anchor !== undefined && anchor !== '' ? `#${anchor}` : '')
	)
}

// Create software wallet table data
const softwareWalletData: TableRow[] = Object.values(ratedSoftwareWallets)
	.map(wallet => {
		const accountTypes = walletSupportedAccountTypes(wallet, 'ALL_VARIANTS')
		const hasErc4337 =
			accountTypes !== null && setContains<AccountType>(accountTypes, AccountType.rawErc4337)
		const hasEip7702 =
			accountTypes !== null && setContains<AccountType>(accountTypes, AccountType.eip7702)
		const hasEoa =
			accountTypes !== null &&
			(hasEip7702 || setContains<AccountType>(accountTypes, AccountType.eoa))
		const typeFor7702 = hasEip7702
			? WalletTypeFor7702.EIP7702
			: hasErc4337
				? WalletTypeFor7702.NON_7702_SMART_WALLET
				: hasEoa
					? WalletTypeFor7702.NON_7702_EOA
					: WalletTypeFor7702.OTHER
		const contract = ((): TableRow['contract'] => {
			for (const variant of setItems<Variant>(getVariants(wallet.variants))) {
				const variantWallet = getVariantResolvedWallet(wallet, variant)

				if (variantWallet === null || variantWallet.features.accountSupport === null) {
					continue
				}

				if (isAccountTypeSupported(variantWallet.features.accountSupport.eip7702)) {
					return variantWallet.features.accountSupport.eip7702.contract
				}

				if (isAccountTypeSupported(variantWallet.features.accountSupport.rawErc4337)) {
					return variantWallet.features.accountSupport.rawErc4337.contract
				}
			}

			return 'NONE'
		})()

		const sortPriority = ((): number => {
			switch (typeFor7702) {
				case WalletTypeFor7702.EIP7702:
					return 0
				case WalletTypeFor7702.NON_7702_SMART_WALLET:
					return 1
				case WalletTypeFor7702.NON_7702_EOA:
					return 2
				case WalletTypeFor7702.OTHER:
					return 3
			}
		})()

		return {
			id: wallet.metadata.id,
			name: wallet.metadata.displayName,
			wallet,
			sortPriority,
			typeFor7702,
			contract,
		}
	})
	.sort((a, b) => a.sortPriority - b.sortPriority)

interface WalletTypeCell {
	typeString: string
	hasSmartWallet: boolean
}

type CellValue = string | WalletTypeCell

export default function Eip7702Table(): React.JSX.Element {
	const columnHelper = createColumnHelper<TableRow>()
	const rankColumn = columnHelper.display({
		id: 'rank',
		header: '#',
		cell: ({ row }): React.ReactNode => row.index + 1,
	})
	const walletNameColumn = columnHelper.accessor(
		(row: TableRow): CellValue => row.wallet.metadata.displayName,
		{
			id: 'wallet',
			header: 'Wallet',
			cell: walletNameCell<TableRow>,
		},
	)
	const walletTypeColumn = columnHelper.display({
		id: 'type',
		header: 'Type',
		cell: (info: CellContext<TableRow, unknown>): React.ReactNode => {
			switch (info.row.original.typeFor7702) {
				case WalletTypeFor7702.EIP7702:
					return (
						<div className='mt-1 flex flex-wrap gap-1'>
							<EipStandardTag standard={eip7702} usePrefix={true} />
						</div>
					)
				case WalletTypeFor7702.NON_7702_SMART_WALLET:
					return (
						<div className='mt-1 flex flex-wrap gap-1'>
							<EipStandardTag standard={erc4337} usePrefix={true} />
						</div>
					)
				case WalletTypeFor7702.NON_7702_EOA:
					return <span>Non-7702 EOA</span>
				case WalletTypeFor7702.OTHER:
					return <span>Non-7702</span>
			}
		},
	})
	const walletContractColumn = columnHelper.display({
		id: 'contract',
		header: 'Contract',
		cell: (info: CellContext<TableRow, unknown>): React.ReactNode => {
			if (info.row.original.contract === 'NONE') {
				return <span style={{ opacity: 0.5 }}>N/A</span>
			}

			const contract = info.row.original.contract

			if (contract === 'UNKNOWN') {
				return <span style={{ opacity: 1 }}>Unknown - Send PR!</span>
			}

			return <ExternalLink url={walletContractUrl(contract.address)} defaultLabel={contract.name} />
		},
	})
	const walletContractSource = columnHelper.display({
		id: 'contract-source',
		header: 'Source',
		cell: (info: CellContext<TableRow, unknown>): React.ReactNode => {
			if (info.row.original.contract === 'NONE') {
				return <span style={{ opacity: 0.5 }}>N/A</span>
			}

			const contract = info.row.original.contract

			if (contract === 'UNKNOWN') {
				return null
			}

			if (!contract.sourceCode.available) {
				return <span style={{ color: 'var(--color-error)' }}>Unavailable</span>
			}

			const sourceRefs = refs(contract.sourceCode)
			const sourceUrl = isNonEmptyArray(sourceRefs)
				? nonEmptyGet(nonEmptyGet(sourceRefs).urls)
				: walletContractUrl(contract.address, 'code')
			const rawUrl = isLabeledUrl(sourceUrl) ? sourceUrl.url : sourceUrl

			return <ExternalLink url={rawUrl} defaultLabel='Available' />
		},
	})
	const walletTransactionBatchingColumn = columnHelper.display({
		id: 'transaction-batching',
		header: 'Batching',
		cell: (info: CellContext<TableRow, unknown>): React.ReactNode => {
			if (info.row.original.contract === 'NONE') {
				return <span style={{ opacity: 0.5 }}>N/A</span>
			}

			return <span style={{ opacity: 0.5 }}>Coming soon</span>
		},
	})
	const columns: Array<ColumnDef<TableRow, CellValue>> = [
		rankColumn,
		walletNameColumn,
		walletTypeColumn,
		walletContractColumn,
		walletContractSource,
		walletTransactionBatchingColumn,
	]

	// Create table
	const table = useReactTable({
		data: softwareWalletData,
		columns,
		getCoreRowModel: getCoreRowModel(),
	})

	// Render table body based on active tab
	const renderTableBody = (): React.ReactNode => {
		return table.getRowModel().rows.map(row => {
			return (
				<tr key={row.id} className={'dark:bg-[#141414] dark:hover:bg-[#1a1a1a]'}>
					{row.getVisibleCells().map(cell => (
						<td
							key={cell.id}
							className={cx(
								'px-4 py-2 dark:text-gray-200',
								cell.column.id === 'rank' ? 'text-center' : '',
							)}
						>
							{flexRender(cell.column.columnDef.cell, cell.getContext())}
						</td>
					))}
				</tr>
			)
		})
	}

	return (
		<div className='overflow-x-auto'>
			<table className='min-w-full divide-y divide-gray-200 dark:divide-gray-700 bg-background'>
				<thead>
					{table.getHeaderGroups().map(headerGroup => (
						<tr className='bg-tertiary' key={headerGroup.id}>
							{headerGroup.headers.map(header => {
								const headerContent = header.column.columnDef.header

								return (
									<th
										key={header.id}
										className={cx(
											'px-4 py-2 text-[14px] text-secondary',
											header.column.id === 'rank' ? 'text-center' : 'text-left',
											header.column.id === 'wallet'
												? 'font-bold'
												: header.column.id === 'type'
													? 'font-semibold'
													: 'font-normal',
										)}
									>
										{headerContent !== undefined && flexRender(headerContent, header.getContext())}
									</th>
								)
							})}
						</tr>
					))}
				</thead>
				<tbody className='divide-y divide-gray-200 dark:divide-gray-700'>{renderTableBody()}</tbody>
			</table>
		</div>
	)
}

// src/views/Eip7702Table.svelte
<script lang="ts">
	// Types/constants
	import { eip7702 } from '@/data/eips/eip-7702'
	import { erc4337 } from '@/data/eips/erc-4337'
	import { ratedSoftwareWallets } from '@/data/software-wallets'
	import type { EVMAddress, SmartWalletContract } from '@/schema/contracts'
	import { AccountType } from '@/schema/features/account-support'
	import type { Variant } from '@/schema/variants'
	import type { RatedWallet } from '@/schema/wallet'

	const WalletTypeFor7702 = {
		EIP7702: 'EIP7702',
		EIP4337: 'EIP4337',
		NON_7702_EOA: 'NON_7702_EOA',
		OTHER: 'OTHER',
	} as const

	type WalletTypeFor7702 = (typeof WalletTypeFor7702)[keyof typeof WalletTypeFor7702]

	const WalletTypeFor7702SortPriority = {
		[WalletTypeFor7702.EIP7702]: 0,
		[WalletTypeFor7702.EIP4337]: 1,
		[WalletTypeFor7702.NON_7702_EOA]: 2,
		[WalletTypeFor7702.OTHER]: 3,
	} as const


	// Props
	let {
		title
	}: {
		title?: string
	} = $props()


	// Functions
	import { isAccountTypeSupported } from '@/schema/features/account-support'
	import { refs } from '@/schema/reference'
	import { isLabeledUrl } from '@/schema/url'
	import { getVariants } from '@/schema/variants'
	import { getVariantResolvedWallet, walletSupportedAccountTypes } from '@/schema/wallet'
	import { isNonEmptyArray, nonEmptyGet, setContains, setItems } from '@/types/utils/non-empty'

	const getWalletTypeFor7702 = (wallet: RatedWallet) => {
		const accountTypes = walletSupportedAccountTypes(wallet, 'ALL_VARIANTS')
		const hasErc4337 =
			accountTypes !== null && setContains<AccountType>(accountTypes, AccountType.rawErc4337)
		const hasEip7702 =
			accountTypes !== null && setContains<AccountType>(accountTypes, AccountType.eip7702)
		const hasEoa =
			accountTypes !== null &&
			(hasEip7702 || setContains<AccountType>(accountTypes, AccountType.eoa))

		return hasEip7702
			? WalletTypeFor7702.EIP7702
			: hasErc4337
				? WalletTypeFor7702.EIP4337
				: hasEoa
					? WalletTypeFor7702.NON_7702_EOA
					: WalletTypeFor7702.OTHER
	}

	const getWalletContract = (wallet: RatedWallet): SmartWalletContract | 'UNKNOWN' | undefined => {
		for (const variant of setItems<Variant>(getVariants(wallet.variants))) {
			const variantWallet = getVariantResolvedWallet(wallet, variant)

			if (variantWallet === null || variantWallet.features.accountSupport === null)
				continue

			if (isAccountTypeSupported(variantWallet.features.accountSupport.eip7702))
				return variantWallet.features.accountSupport.eip7702.contract

			if (isAccountTypeSupported(variantWallet.features.accountSupport.rawErc4337))
				return variantWallet.features.accountSupport.rawErc4337.contract
		}
	}


	// State
	let activeFilters: Filters<RatedWallet>['$$prop_def']['activeFilters'] = $state(new Set())
	let filteredWallets = $state<RatedWallet[]>([])


	// Actions
	let toggleFilterById: Filters<RatedWallet>['$$prop_def']['toggleFilterById'] = $state()
	let toggleFilter: Filters<RatedWallet>['$$prop_def']['toggleFilter'] = $state()


	// Components
	import ExternalLinkIcon from 'lucide-static/icons/external-link.svg?raw'
	import KeyIcon from 'lucide-static/icons/key.svg?raw'

	import Filters from '@/components/Filters.svelte'
	import Table from '@/components/Table.svelte'
	import Tooltip from '@/components/Tooltip.svelte'
	import EipDetails from '@/views/EipDetails.svelte'
</script>


<header
	data-sticky="inline"
	data-row="wrap"
>
	{#if title}
		<h2>{title}</h2>
	{/if}

	<Filters
		items={Object.values(ratedSoftwareWallets)}
		filterGroups={[
			{
				id: 'accountType',
				label: 'Account Type',
				displayType: 'group',
				exclusive: false,
				filters: [
					{
						id: 'accountType-eip7702',
						label: 'EIP-7702',
						icon: KeyIcon,
						filterFunction: wallet => getWalletTypeFor7702(wallet) === WalletTypeFor7702.EIP7702,
					},
					{
						id: 'accountType-erc4337',
						label: 'ERC-4337',
						icon: KeyIcon,
						filterFunction: wallet => getWalletTypeFor7702(wallet) === WalletTypeFor7702.EIP4337,
					},
					{
						id: 'accountType-eoa',
						label: 'EOA',
						icon: KeyIcon,
						filterFunction: wallet => getWalletTypeFor7702(wallet) === WalletTypeFor7702.NON_7702_EOA,
					},
				],
			},
		]}
		bind:activeFilters
		bind:filteredItems={filteredWallets}
		bind:toggleFilter
		bind:toggleFilterById
	/>
</header>

<Table
	rows={filteredWallets}
	rowId={wallet => wallet.metadata.id}

	columns={[
		{
			id: 'wallet',
			name: 'Wallet',
			value: wallet => wallet.metadata.displayName,
			isSticky: true,
			sort: {
				defaultDirection: 'asc',
			},
		},
		{
			id: 'type',
			name: 'Type',
			value: wallet => WalletTypeFor7702SortPriority[getWalletTypeFor7702(wallet)],
			sort: {
				isDefault: true,
				defaultDirection: 'asc',
			},
		},
		{
			id: 'contract',
			name: 'Contract',
			value: wallet => getWalletContract(wallet),
		},
		{
			id: 'batching',
			name: 'Batching',
			value: () => 'Coming soon',
		},
	]}
>
	{#snippet Cell({ row: wallet, column, value })}
		{#if column.id === 'wallet'}
			<div class="wallet-info" data-row>
				<span class="row-count" data-row="center"></span>

				<img
					src={`/images/wallets/${wallet.metadata.id}.svg`}
					alt={wallet.metadata.displayName}
					class="wallet-icon"
					onerror={e => {
						const target = e.target as HTMLImageElement
						if (target) target.src = '/images/wallets/default.svg'
					}}
				/>

				<div class="name">
					<h3>
						<a
							href={`/${wallet.metadata.id}/`}
						>
							{wallet.metadata.displayName}
						</a>
					</h3>
				</div>
			</div>

		{:else if column.id === 'type'}
			{@const typeFor7702 = getWalletTypeFor7702(wallet)}

			{#if typeFor7702 === WalletTypeFor7702.EIP7702}
				<Tooltip
					placement="inline-end"
				>
					<button
						data-tag="eip"
						aria-label="Filter by EIP-7702"
						onclick={e => {
							e.stopPropagation()
							toggleFilterById!('accountType-eip7702')
						}}
					>
						EIP-7702
					</button>

					{#snippet TooltipContent()}
						<EipDetails eip={eip7702} />
					{/snippet}
				</Tooltip>
			{:else}
				{#if typeFor7702 === WalletTypeFor7702.EIP4337}
					<Tooltip
						placement="inline-end"
					>
						<button
							data-tag="eip"
							aria-label="Filter by ERC-4337"
							onclick={e => {
								e.stopPropagation()
								toggleFilterById!('accountType-erc4337')
							}}
						>
							ERC-4337
						</button>

						{#snippet TooltipContent()}
							<EipDetails eip={erc4337} />
						{/snippet}
					</Tooltip>
				{:else}
					{#if typeFor7702 === WalletTypeFor7702.NON_7702_EOA}
						<button
							data-tag="eoa"
							aria-label="Filter by EOA"
							onclick={e => {
								e.stopPropagation()
								toggleFilterById!('accountType-eoa')
							}}
						>
							EOA
						</button>
					{/if}
				{/if}

				<small class="muted-text">(non-7702)</small>
			{/if}

		{:else if column.id === 'contract'}
			{@const contract = getWalletContract(wallet)}

			{#if contract === undefined}
				<span class="muted-text">–</span>
			{:else if contract === 'UNKNOWN'}
				<span class="muted-text">Unknown</span>
			{:else}
				{@const getContractUrl = (contractAddress: EVMAddress, anchor?: string) =>
					`https://etherscan.io/address/${contractAddress}${anchor ? `#${anchor}` : ''}`
				}

				<div class="contract-info">
					<strong>
						<a
							href={getContractUrl(contract.address)}
							target="_blank"
							rel="noopener noreferrer"
						>
							{contract.name}
						</a>
					</strong>
				</div>

				<small>
					{#if contract.sourceCode.available}
						{@const sourceRefs = refs(contract.sourceCode)}
						{@const sourceUrl =
							isNonEmptyArray(sourceRefs) ?
								nonEmptyGet(nonEmptyGet(sourceRefs).urls)
							:
								getContractUrl(contract.address, 'code')
						}
						{@const rawUrl = isLabeledUrl(sourceUrl) ? sourceUrl.url : sourceUrl}

						<a
							href={rawUrl}
							target="_blank"
							rel="noopener noreferrer"
							class="source-link"
						>
							Source code
							<span>{@html ExternalLinkIcon}</span>
						</a>
					{:else}
						<span class="muted-text">Source unavailable</span>
					{/if}
				</small>
			{/if}

		{:else if column.id === 'batching'}
			{@const contract = getWalletContract(wallet)}

		<span class="muted-text">Coming soon</span>

		{:else}
			{value}
		{/if}
	{/snippet}
</Table>


<style>
	.wallet-info {
		gap: 0.85em;
		padding: 0.5em 0;

		.row-count {
			width: 1.25em;
			height: 1.25em;

			font-weight: 600;
			color: var(--text-secondary);

			&::before {
				content: counter(TableRowCount);
			}

			:global([data-disabled]) &::before {
				content: '–';
			}
		}

		.wallet-icon {
			filter: drop-shadow(rgba(255, 255, 255, 0.1) 0px 0px 4.66667px);
			width: 2.25em;
			height: 2.25em;
			object-fit: contain;
			border-radius: 0.25em;
		}

		.name {
			font-size: 0.85em;

			h3 {
				font-weight: 600;

				a {
					color: var(--text-primary);

					&:not(:hover) {
						text-decoration: none;
					}
				}
			}

		}
	}

	[data-tag] {
		&:is(button) {
			display: inline-flex;
		}
	}

	.muted-text {
		color: var(--text-secondary);
	}
</style>
