// src/views/attributes/privacy/AddressCorrelationDetails.svelte
<script lang="ts">
	// Types/constants
	import type { WalletAddressLinkableBy } from '@/schema/attributes/privacy/address-correlation'
	import type { WalletMetadata } from '@/schema/wallet'
	import { ContentType } from '@/types/content'
	import type { NonEmptyArray } from '@/types/utils/non-empty'
	import { getWalletEvalStrings } from '@/utils/evaluation-content'

	type LeakInfo = {
		key: string
		value: string
	}

	// Props
	const {
		wallet,
		linkables,
	}: {
		wallet: { metadata: WalletMetadata }
		linkables?: NonEmptyArray<WalletAddressLinkableBy> | undefined
	} = $props()


	// Functions
	import { compareUserInfo, userInfoName } from '@/schema/features/privacy/data-collection'
	import { mergeRefs } from '@/schema/reference'
	import { isUrl } from '@/schema/url'
	import { nonEmptyGet, nonEmptySorted } from '@/types/utils/non-empty'

	const joinedListText = (
		items: LeakInfo[],
		separator = ', ',
		lastSeparator = ' and ',
	): string => (
		items
			.map((item, index) => (
				item.value + (
					index === items.length - 2 ?
						lastSeparator
					: index !== items.length - 1 ?
						separator
					:
						''
				)
			))
			.join('')
	)


	// Components
	import Typography from '@/components/Typography.svelte'
</script>


{#if !linkables}
	<Typography
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: 'By default, **{{WALLET_NAME}}** allows your wallet address to be correlated with your personal information:'
		}}
		strings={getWalletEvalStrings(wallet)}
	/>
{:else}
	{@const sortedLinkables = nonEmptySorted(
		linkables,
		(linkableA: WalletAddressLinkableBy, linkableB: WalletAddressLinkableBy) => (
			linkableA.by === 'onchain' ?
				1
			: linkableB.by === 'onchain' ?
				-1
			:
				compareUserInfo(linkableA.info, linkableB.info)
		),
		true,
	)}

	{@const bySource = (() => {
		const map = new Map<string, NonEmptyArray<WalletAddressLinkableBy>>()

		for (const linkable of sortedLinkables) {
			const sourceName = typeof linkable.by === 'string' ? linkable.by : linkable.by.name
			const forSource = map.get(sourceName)

			if (forSource === undefined) {
				map.set(sourceName, [linkable] as NonEmptyArray<WalletAddressLinkableBy>)
			} else {
				forSource.push(linkable)
			}
		}

		return map
	})()}

	{@const leaksList = Array.from(
		bySource,
		([sourceName, linkables]) => ({
			sourceName,
			linkables,
			linkableInfos: linkables
				.map(linkable => ({
					key: linkable.info,
					value: userInfoName(linkable.info).long
				}))
				.filter((info, index, allInfo) =>
					allInfo.slice(index + 1).every(otherInfo => otherInfo.key !== info.key)
				),
			refs: mergeRefs(...linkables.flatMap(linkable => linkable.refs)),
			entity: nonEmptyGet(linkables).by
		})
	)}

	{@const leaksText = leaksList.map(leak => (
		leak.entity === 'onchain' ?
			`- An onchain record permanently associates your **${joinedListText(leak.linkableInfos)}** with your wallet address.`
		:
			(() => {
				const privacyPolicyText = (
					isUrl(leak.entity.privacyPolicy) ?
						` ([Privacy policy](${typeof leak.entity.privacyPolicy === 'string' ? leak.entity.privacyPolicy : leak.entity.privacyPolicy.url}))`
					:
						''
				)

				return `- **${leak.entity.name}**${privacyPolicyText} may link your wallet address to your **${joinedListText(leak.linkableInfos)}**.`
			})()
	)).join('\n')}

	<Typography
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: `By default, **{{WALLET_NAME}}** allows your wallet address to be correlated with your personal information:

${leaksText}`
		}}
		strings={getWalletEvalStrings(wallet)}
	/>
{/if}

// src/ui/molecules/attributes/privacy/AddressCorrelationDetails.tsx
import type { WalletAddressLinkableBy } from '@/schema/attributes/privacy/address-correlation'
import { compareLeakedInfo, leakedInfoName } from '@/schema/features/privacy/data-collection'
import { mergeRefs } from '@/schema/reference'
import { type NonEmptyArray, nonEmptyGet, nonEmptySorted } from '@/types/utils/non-empty'
import { Typography } from '@mui/material'
import type React from 'react'
import { JoinedList } from '../../../atoms/JoinedList'
import { ExternalLink } from '../../../atoms/ExternalLink'
import { ReferenceLinks } from '../../../atoms/ReferenceLinks'
import { subsectionWeight } from '@/components/constants'
import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon'
import { isUrl } from '@/schema/url'
import type { AddressCorrelationDetailsProps } from '@/types/content/address-correlation-details'
import { EntityLink } from '@/ui/atoms/EntityLink'

export function AddressCorrelationDetails({
	wallet,
	value,
	linkables,
}: AddressCorrelationDetailsProps): React.JSX.Element {
	const bySource = new Map<string, NonEmptyArray<WalletAddressLinkableBy>>()
	for (const linkable of nonEmptySorted(
		linkables,
		(linkableA: WalletAddressLinkableBy, linkableB: WalletAddressLinkableBy) => {
			if (linkableA.by === 'onchain') {
				return 1
			}
			if (linkableB.by === 'onchain') {
				return -1
			}
			return compareLeakedInfo(linkableA.info, linkableB.info)
		},
		true,
	)) {
		const sourceName = typeof linkable.by === 'string' ? linkable.by : linkable.by.name
		const forSource = bySource.get(sourceName)
		if (forSource === undefined) {
			bySource.set(sourceName, [linkable])
		} else {
			forSource.push(linkable)
		}
	}
	const leaksList: React.ReactNode[] = []
	bySource.forEach((linkables, sourceName) => {
		const linkableInfos = (
			<JoinedList
				data={linkables.map(linkable => ({
					key: linkable.info,
					value: <strong>{leakedInfoName(linkable.info, wallet.metadata).long}</strong>,
				}))}
			/>
		)
		const refs = mergeRefs(...linkables.flatMap(linkable => linkable.refs))
		const entity = nonEmptyGet(linkables).by
		if (entity === 'onchain') {
			leaksList.push(
				<li key={sourceName}>
					<Typography>
						An onchain record permanently associates your {linkableInfos} with your wallet address.{' '}
						<ReferenceLinks ref={refs} />
					</Typography>
				</li>,
			)
			return
		}
		leaksList.push(
			<li key={sourceName}>
				<Typography>
					<EntityLink entity={entity} />{' '}
					{isUrl(entity.privacyPolicy) ? (
						<>
							{' ('}
							<ExternalLink url={entity.privacyPolicy} defaultLabel="Privacy policy" />
							{')'}
						</>
					) : null}{' '}
					may link your wallet address to your {linkableInfos}. <ReferenceLinks ref={refs} />
				</Typography>
			</li>,
		)
	})
	return (
		<>
			<WrapRatingIcon rating={value.rating}>
				<Typography fontWeight={subsectionWeight}>
					By default, {wallet.metadata.displayName} allows your wallet address to be correlated with
					your personal information:
				</Typography>
				<ul style={{ paddingLeft: '1.5rem', marginBottom: '0px', fontWeight: subsectionWeight }}>
					{leaksList}
				</ul>
			</WrapRatingIcon>
		</>
	)
}
