// src/views/attributes/self-sovereignty/TransactionInclusionDetails.svelte
<script lang="ts">
	// Types/constants
	import type { L1BroadcastSupport } from '@/schema/attributes/self-sovereignty/transaction-inclusion'
	import type { TransactionSubmissionL2Type } from '@/schema/features/self-sovereignty/transaction-submission'
	import type { WalletMetadata } from '@/schema/wallet'
	import { ContentType } from '@/types/content'


	// Props
	const {
		wallet,
		supportsL1Broadcast,
		supportAnyL2Transactions = [],
		supportForceWithdrawal = [],
		unsupportedL2s = [],
	}: {
		wallet: { metadata: WalletMetadata }
		supportsL1Broadcast?: L1BroadcastSupport
		supportAnyL2Transactions?: TransactionSubmissionL2Type[]
		supportForceWithdrawal?: TransactionSubmissionL2Type[]
		unsupportedL2s?: TransactionSubmissionL2Type[]
	} = $props()


	// Functions
	import { transactionSubmissionL2TypeName } from '@/schema/features/self-sovereignty/transaction-submission'


	// Components
	import Typography from '@/components/Typography.svelte'
</script>


{#if supportAnyL2Transactions.length || supportForceWithdrawal.length || unsupportedL2s.length}
	{@const allSupportedForceWithdrawals = [
			...supportAnyL2Transactions,
			...supportForceWithdrawal,
		].toSorted()}

	{#if allSupportedForceWithdrawals.length}
		<Typography
			content={{
				contentType: ContentType.MARKDOWN,
				markdown: `**{{WALLET_NAME}}** supports L2 force-inclusion withdrawal transactions on **${allSupportedForceWithdrawals.map(l2Type => transactionSubmissionL2TypeName(l2Type)).join(', ')}** L2s.\n\nThis means users may withdraw funds from these L2s without relying on intermediaries.`,
			}}
			strings={{ WALLET_NAME: wallet.metadata.displayName }}
		/>
	{/if}

	{#if unsupportedL2s.length}
		<Typography
			content={{
				contentType: ContentType.MARKDOWN,
				markdown: `${allSupportedForceWithdrawals.length ? 'However, it' : '**{{WALLET_NAME}}**'} does not support L2 force-inclusion withdrawal transactions on **${unsupportedL2s.map(transactionSubmissionL2TypeName).join(' or ')}** L2s.\n\nThis means users rely on intermediaries in order to withdraw their funds from these L2s.`,
			}}
			strings={{ WALLET_NAME: wallet.metadata.displayName }}
		/>
	{/if}
{/if}
<Typography
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: (
			supportsL1Broadcast === 'NO' ?
				'**{{WALLET_NAME}}** does not support Ethereum peer-to-peer gossiping nor connecting to a user\'s self-hosted Ethereum node.\n\nTherefore, L1 transactions are subject to censorship by intermediaries.'
			: supportsL1Broadcast === 'OWN_NODE' ?
				'**{{WALLET_NAME}}** supports connecting to a user\'s self-hosted Ethereum node, which can be used to broadcast L1 transactions without trusting intermediaries.'
			: supportsL1Broadcast === 'SELF_GOSSIP' ?
				'**{{WALLET_NAME}}** supports directly gossipping over Ethereum\'s peer-to-peer network, allowing L1 transactions to be reliably included without trusting intermediaries.'
			:
				''
		),
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

// src/ui/molecules/attributes/self-sovereignty/TransactionInclusionDetails.tsx
import { Typography } from '@mui/material'
import React from 'react'

import { subsectionWeight } from '@/components/constants'
import { transactionSubmissionL2TypeName } from '@/schema/features/self-sovereignty/transaction-submission'
import type { TransactionInclusionDetailsProps } from '@/types/content/transaction-inclusion-details'
import { commaListPrefix } from '@/types/utils/text'

import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon'

export function TransactionInclusionDetails({
	wallet,
	value,
	supportsL1Broadcast,
	supportAnyL2Transactions,
	supportForceWithdrawal,
	unsupportedL2s,
}: TransactionInclusionDetailsProps): React.JSX.Element {
	const allSupportedForceWithdrawals = supportAnyL2Transactions
		.concat(supportForceWithdrawal)
		.slice()
		.sort()

	return (
		<WrapRatingIcon rating={value.rating}>
			{allSupportedForceWithdrawals.length > 0 && (
				<>
					<Typography fontWeight={subsectionWeight}>
						{wallet.metadata.displayName} supports L2 force-inclusion withdrawal transactions on{' '}
						{allSupportedForceWithdrawals.map((l2Type, index) => (
							<React.Fragment key={l2Type}>
								{commaListPrefix(index, allSupportedForceWithdrawals.length)}
								<strong>{transactionSubmissionL2TypeName(l2Type)}</strong>
							</React.Fragment>
						))}{' '}
						L2s.
					</Typography>
					<Typography fontWeight={subsectionWeight}>
						This means users may withdraw funds from these L2s without relying on intermediaries.
					</Typography>
				</>
			)}
			{unsupportedL2s.length > 0 && (
				<>
					<Typography fontWeight={subsectionWeight}>
						{allSupportedForceWithdrawals.length === 0
							? wallet.metadata.displayName
							: ' However, it'}{' '}
						does not support L2 force-inclusion withdrawal transactions on{' '}
						{unsupportedL2s.map((l2Type, index) => (
							<React.Fragment key={l2Type}>
								{commaListPrefix(index, unsupportedL2s.length, 'or')}
								<strong>{transactionSubmissionL2TypeName(l2Type)}</strong>
							</React.Fragment>
						))}{' '}
						L2s.
					</Typography>
					<Typography fontWeight={subsectionWeight}>
						This means users rely on intermediaries in order to withdraw their funds from these L2s.
					</Typography>
				</>
			)}
			{(() => {
				switch (supportsL1Broadcast) {
					case 'NO':
						return (
							<>
								<Typography fontWeight={subsectionWeight}>
									{wallet.metadata.displayName} does not support Ethereum peer-to-peer gossiping nor
									connecting to a user&apos;s self-hosted Ethereum node.
								</Typography>
								<Typography fontWeight={subsectionWeight}>
									Therefore, L1 transactions are subject to censorship by intermediaries.
								</Typography>
							</>
						)
					case 'OWN_NODE':
						return (
							<Typography fontWeight={subsectionWeight}>
								{wallet.metadata.displayName} supports connecting to a user&apos;s self-hosted
								Ethereum node, which can be used to broadcast L1 transactions without trusting
								intermediaries.
							</Typography>
						)
					case 'SELF_GOSSIP':
						return (
							<Typography fontWeight={subsectionWeight}>
								{wallet.metadata.displayName} supports directly gossipping over Ethereum&apos;s
								peer-to-peer network, allowing L1 transactions to be reliably included without
								trusting intermediaries.
							</Typography>
						)
				}
			})()}
		</WrapRatingIcon>
	)
}
