// src/views/attributes/security/ChainVerificationDetails.svelte
<script lang="ts">
	// Types/constants
	import type { EthereumL1LightClient } from '@/schema/features/security/light-client'
	import { ethereumL1LightClientUrl } from '@/schema/features/security/light-client'
	import type { FullyQualifiedReference } from '@/schema/reference'
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'
	import type { NonEmptyArray } from '@/types/utils/non-empty'
	import { commaListPrefix } from '@/types/utils/text'


	// Props
	const {
		wallet,
		lightClients,
		refs,
	}: {
		wallet: RatedWallet
		lightClients?: NonEmptyArray<EthereumL1LightClient>
		refs?: FullyQualifiedReference[]
	} = $props()


	// Components
	import Typography from '@/components/Typography.svelte'
	import ReferenceLinks from '@/views/ReferenceLinks.svelte'
</script>


<Typography
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: (
			!lightClients || lightClients.length === 0 ?
				'**{{WALLET_NAME}}** does not perform L1 chain state verification.'
			:
				`**{{WALLET_NAME}}** performs L1 chain state verification using ${lightClients.map((client: EthereumL1LightClient, i: number) => {
					const clientUrl = ethereumL1LightClientUrl(client)

					return `${commaListPrefix(i, lightClients.length)}[${client}](${typeof clientUrl === 'string' ? clientUrl : clientUrl.url})`
				}).join('')}${lightClients.length === 1 ? ' light client.' : ' light clients.'}`
		)
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

{#if refs && refs.length > 0}
	<ReferenceLinks references={refs} />
{/if}

// src/ui/molecules/attributes/security/ChainVerificationDetails.tsx
import { Typography } from '@mui/material';
import React from 'react';

import { subsectionWeight } from '@/components/constants';
import { ethereumL1LightClientUrl } from '@/schema/features/security/light-client';
import type { ChainVerificationDetailsProps } from '@/types/content/chain-verification-details';
import { nonEmptyMap } from '@/types/utils/non-empty';
import { commaListPrefix } from '@/types/utils/text';

import { ExternalLink } from '../../../atoms/ExternalLink';
import { ReferenceList } from '../../../atoms/ReferenceList';
import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon';

export function ChainVerificationDetails({
	wallet,
	value,
	lightClients,
	refs,
}: ChainVerificationDetailsProps): React.JSX.Element {
	return (
		<WrapRatingIcon rating={value.rating}>
			<Typography fontWeight={subsectionWeight}>
				<React.Fragment key='start'>
					{wallet.metadata.displayName} performs L1 chain state verification using
					the{' '}
				</React.Fragment>
				{nonEmptyMap(lightClients, (lightClient, index) => (
					<React.Fragment key={lightClient}>
						{commaListPrefix(index, lightClients.length)}
						<ExternalLink url={ethereumL1LightClientUrl(lightClient)} />
					</React.Fragment>
				))}
				<React.Fragment key='end'>
					{' '}
					light client{lightClients.length === 1 ? '' : 's'}.
				</React.Fragment>
				{refs.length === 0 ? null : (
					<React.Fragment key='refs'>
						{' '}
						<ReferenceList key='refList' ref={refs} />
					</React.Fragment>
				)}
			</Typography>
		</WrapRatingIcon>
	);
}
