// src/views/attributes/security/SecurityAuditsDetails.svelte
<script lang="ts">
	// Types/constants
	import type { SecurityAuditsValue } from '@/schema/attributes/security/security-audits'
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'
	import { SecurityFlawSeverity } from '@/schema/features/security/security-audits'

	const securityFlawSeverities = {
		[SecurityFlawSeverity.CRITICAL]: {
			icon: '🚨',
			label: 'Critical',
		},
		[SecurityFlawSeverity.HIGH]: {
			icon: '‼️',
			label: 'High',
		},
		[SecurityFlawSeverity.MEDIUM]: {
			icon: '⚠️',
			label: 'Medium',
		},
	} as const satisfies Record<
		SecurityFlawSeverity,
		{
			icon: string
			label: string
		}
	>


	// Props
	const {
		wallet,
		value,
		auditedInLastYear,
		hasUnaddressedFlaws,
	}: {
		wallet: RatedWallet
		value: SecurityAuditsValue
		auditedInLastYear?: boolean
		hasUnaddressedFlaws?: boolean
	} = $props()


	// Functions
	import { securityAuditId, type UnpatchedSecurityFlaw } from '@/schema/features/security/security-audits'
	import { toFullyQualified } from '@/schema/reference'
	import { isUrl } from '@/schema/url'


	// Components
	import Typography from '@/components/Typography.svelte'
	import ReferenceLinks from '@/views/ReferenceLinks.svelte'
</script>

{#if value.securityAudits.length === 0}
	<Typography
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: '**{{WALLET_NAME}}** has not undergone any security audits.',
		}}
		strings={{ WALLET_NAME: wallet.metadata.displayName }}
	/>
{:else}
	{@const securityAudits = (
		value
			.securityAudits
			.toSorted((a, b) => (
				new Date(b.auditDate).getTime() - new Date(a.auditDate).getTime()
			))
	)}

	{@const mostRecentAudit = securityAudits[0]}

	{@const anyAuditHasUnfixedFlaws = (
		securityAudits
			.some((audit) => (
				Array.isArray(audit.unpatchedFlaws)
				&& (
					audit.unpatchedFlaws
						.some((flaw: UnpatchedSecurityFlaw) => (
							flaw.presentStatus === 'NOT_FIXED'
						))
				)
			))
	)}

	<Typography
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: `**{{WALLET_NAME}}** was last audited on ${Intl.DateTimeFormat(undefined, { dateStyle: 'long' }).format(new Date(mostRecentAudit.auditDate))}${auditedInLastYear ? '.' : ', which was over a year ago.'}${hasUnaddressedFlaws ? ' There remain unaddressed security flaws in the codebase.' : ''}`,
		}}
		strings={{ WALLET_NAME: wallet.metadata.displayName }}
	/>

	<section data-column="gap-2">
		{#each securityAudits as audit, index (securityAuditId(audit))}
			{@const isMostRecent = index === 0}
			{@const hasUnfixedFlaws = Array.isArray(audit.unpatchedFlaws) && audit.unpatchedFlaws.some((flaw: UnpatchedSecurityFlaw) => flaw.presentStatus === 'NOT_FIXED')}
			{@const flawGroups = Array.isArray(audit.unpatchedFlaws) ? Map.groupBy(audit.unpatchedFlaws, (flaw: UnpatchedSecurityFlaw) => flaw.severityAtAuditPublication) : null}
			{@const hasFlaws = flawGroups && flawGroups.size > 0}

			<details
				data-card="secondary"
				open={
					anyAuditHasUnfixedFlaws ?
						hasUnfixedFlaws
					:
						isMostRecent
				}
			>
				<summary>
					<header data-row="wrap wrap-first-last">
						<div 
							data-row-item="flexible basis-1"
							data-row="start wrap gap-2"
						>
							<h4>
								Audit by 
								<cite>
									{#if isUrl(audit.auditor.url)}
										<a
											href={typeof audit.auditor.url === 'string'
												? audit.auditor.url
												: audit.auditor.url.url}
											target="_blank"
											rel="noopener noreferrer"
										>
											{audit.auditor.name}
										</a>
									{:else}
										{audit.auditor.name}
									{/if}
								</cite>
							</h4>

							{#if hasFlaws && flawGroups}
								<div data-row="gap-1 wrap">
									{#each [SecurityFlawSeverity.CRITICAL, SecurityFlawSeverity.HIGH, SecurityFlawSeverity.MEDIUM] as severity}
										{#if flawGroups.has(severity)}
											{@const flaws = flawGroups.get(severity)!}

											<data	
												data-badge="small"
												value={severity}
												title="{securityFlawSeverities[severity].label} severity flaws"
											>
												{securityFlawSeverities[severity].icon}
												{securityFlawSeverities[severity].label} Severity
												({flaws.length})
											</data>
										{/if}
									{/each}
								</div>
							{/if}
						</div>

						<time datetime={audit.auditDate}>
							{
								Intl.DateTimeFormat(undefined, { dateStyle: 'long' })
									.format(
										new Date(audit.auditDate),
									)
							}
						</time>
					</header>
				</summary>

				<section data-column="gap-4">
					{#if audit.unpatchedFlaws === 'NONE_FOUND'}
						<p>No security flaws of severity level medium or higher were found.</p>
					{:else if audit.unpatchedFlaws === 'ALL_FIXED'}
						<p>All security flaws of severity level medium or higher were addressed.</p>
					{:else if Array.isArray(audit.unpatchedFlaws) && audit.unpatchedFlaws.length > 0}
						<p>
							The following security flaws were identified{!hasUnfixedFlaws ? ' and have all been addressed since' : ''}:
						</p>
						<ul class="flaws-list" data-list>
							{#each audit.unpatchedFlaws as flaw (flaw.name)}
								<li
									data-list-item-marker={securityFlawSeverities[flaw.severityAtAuditPublication].icon}
								>
									<span data-row="wrap wrap-first-last">
										<span data-row-item="flexible basis-2">
											<strong>{securityFlawSeverities[flaw.severityAtAuditPublication].label}</strong>:
											{#if flaw.presentStatus === 'FIXED'}
												<s class="fixed-flaw">{flaw.name}</s>
											{:else}
												<span>{flaw.name}</span>
											{/if}
										</span>
										<data
											data-badge="small"
											value={flaw.presentStatus}
											style:--accent={flaw.presentStatus === 'FIXED' ? 'var(--rating-pass)' : 'var(--rating-fail)'}
										>
											{flaw.presentStatus === 'FIXED' ? 'Fixed' : 'Not fixed'}
										</data>
									</span>
								</li>
							{/each}
						</ul>
					{/if}

					{#if audit.ref}
						<ReferenceLinks references={toFullyQualified(audit.ref)} />
					{/if}
				</section>
			</details>
		{/each}
	</section>
{/if}


<style>
	.fixed-flaw {
		opacity: 0.75;
	}

	cite {
		font-style: normal;
	}
</style>

// src/ui/molecules/attributes/security/SecurityAuditsDetails.tsx
import { Typography } from '@mui/material';
import React from 'react';

import { subsectionWeight } from '@/components/constants';
import {
  securityAuditId,
  securityFlawSeverityName,
} from '@/schema/features/security/security-audits';
import { toFullyQualified } from '@/schema/reference';
import type { SecurityAuditsDetailsProps } from '@/types/content/security-audits-details';
import { dateCompare } from '@/types/date';
import { isNonEmptyArray, nonEmptyGet, nonEmptyMap, nonEmptySorted } from '@/types/utils/non-empty';
import { EntityLink } from '@/ui/atoms/EntityLink';
import { ReferenceLinks } from '@/ui/atoms/ReferenceLinks';

import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon';

export function SecurityAuditsDetails({
  wallet,
  value,
  auditedInLastYear,
  hasUnaddressedFlaws,
}: SecurityAuditsDetailsProps): React.JSX.Element {
  const audits = value.securityAudits;

  if (!isNonEmptyArray(audits)) {
    return (
      <WrapRatingIcon rating={value.rating}>
        <Typography fontWeight={subsectionWeight}>
          {wallet.metadata.displayName} has not undergone any security audits.
        </Typography>
      </WrapRatingIcon>
    );
  }

  const sortedAudits = nonEmptySorted(
    audits,
    (audit1, audit2) => dateCompare(audit1.auditDate, audit2.auditDate),
    true /* Reverse */,
  );
  const mostRecentAudit = nonEmptyGet(sortedAudits);

  return (
    <>
      <WrapRatingIcon rating={value.rating}>
        <Typography fontWeight={subsectionWeight}>
          {wallet.metadata.displayName} was last audited on {mostRecentAudit.auditDate}
          {auditedInLastYear ? '.' : ', which was over a year ago.'}{' '}
          <ReferenceLinks references={toFullyQualified(mostRecentAudit.ref)} />
          {hasUnaddressedFlaws && ' There remains unaddressed security flaws in the codebase.'}
        </Typography>
      </WrapRatingIcon>
      <div className='max-h-48 overflow-y-auto border p-2 rounded-md'>
        <ul>
          {nonEmptyMap(sortedAudits, audit => (
            <li key={securityAuditId(audit)}>
              <strong>{audit.auditDate}</strong>{' '}
              <ReferenceLinks references={toFullyQualified(audit.ref)} /> by{' '}
              <EntityLink entity={audit.auditor} />.{' '}
              <React.Fragment key='unpatchedFlaws'>
                {audit.unpatchedFlaws === 'NONE_FOUND' &&
                  'No security flaws of severity level medium or higher were found.'}
                {audit.unpatchedFlaws === 'ALL_FIXED' &&
                  'All security flaws of severity level medium or higher were addressed.'}
                {Array.isArray(audit.unpatchedFlaws) && (
                  <>
                    The following security flaws were identified
                    {!nonEmptyMap(audit.unpatchedFlaws, flaw => flaw.presentStatus).includes(
                      'NOT_FIXED',
                    ) && ' and have all been addressed since'}
                    :
                    <ul>
                      {nonEmptyMap(audit.unpatchedFlaws, flaw => (
                        <React.Fragment key={flaw.name}>
                          <li>
                            <strong>
                              {securityFlawSeverityName(flaw.severityAtAuditPublication)}
                            </strong>
                            :{' '}
                            {flaw.presentStatus === 'FIXED' ? (
                              <>
                                <Typography
                                  sx={{
                                    textDecoration: 'line-through',
                                    opacity: 0.75,
                                  }}
                                >
                                  {flaw.name}
                                </Typography>{' '}
                                (<strong>Fixed</strong>)
                              </>
                            ) : (
                              <>
                                {flaw.name} (<strong>Not fixed</strong>)
                              </>
                            )}
                          </li>
                        </React.Fragment>
                      ))}
                    </ul>
                  </>
                )}
              </React.Fragment>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
