// src/ui/molecules/attributes/transparency/FundingDetails.tsx
import type React from 'react';

import { subsectionWeight } from '@/components/constants';
import {
  monetizationStrategies,
  monetizationStrategyName,
} from '@/schema/features/transparency/monetization';
import { refs } from '@/schema/reference';
import type { FundingDetailsProps } from '@/types/content/funding-details';

import { JoinedList } from '../../../atoms/JoinedList';
import { ReferenceList } from '../../../atoms/ReferenceList';
import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon';

export function FundingDetails({
  wallet,
  value,
  monetization,
}: FundingDetailsProps): React.JSX.Element {
  const strategies = monetizationStrategies(monetization)
    .filter(({ value }) => value === true)
    .map(({ strategy }) => strategy);
  const ref = refs(monetization);

  return (
    <WrapRatingIcon rating={value.rating}>
      <div style={{ fontWeight: subsectionWeight }}>
        <strong>{wallet.metadata.displayName}</strong> is funded by{' '}
        <JoinedList
          data={strategies.map(strategy => ({
            key: strategy,
            value: monetizationStrategyName(strategy),
          }))}
        />
        . <ReferenceList ref={ref} ulStyle={{ paddingLeft: '1.5rem', marginBottom: '0px' }} />
      </div>
    </WrapRatingIcon>
  );
}

// src/ui/molecules/attributes/transparency/FundingDetails.svelte
<script lang="ts">
	// Types/constants
	import type { FundingValue } from '@/schema/attributes/transparency/funding'
	import type { RatedWallet } from '@/schema/wallet'
	import { 
		type Monetization,
		monetizationStrategies,
		monetizationStrategyName
	} from '@/schema/features/transparency/monetization'
	import { ContentType } from '@/types/content'
	import { refs } from '@/schema/reference'

	// Props
	let {
		wallet,
		value,
		monetization,
	}: {
		wallet: RatedWallet
		value: FundingValue
		monetization: Monetization | undefined
	} = $props()

	// Components
	import ReferenceLinks from '@/ui/atoms/ReferenceLinks.svelte'
	import Typography from '@/ui/atoms/Typography.svelte'
</script>

<Typography 
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: (
			monetization ?
				(() => {
					const strategies = monetizationStrategies(monetization)
						.filter(({ value }) => value === true)
						.map(({ strategy }) => strategy)
					const strategiesText = strategies.length === 0 ? 'unknown sources' : strategies.map(strategy => monetizationStrategyName(strategy)).join(', ')
					return `**{{WALLET_NAME}}** is funded by **${strategiesText}**.`
				})()
			:
				`**{{WALLET_NAME}}** is funded by **unknown sources**.`
		)
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

{#if monetization}
	{@const references = refs(monetization)}
	{#if references.length > 0}
		<hr>

		<ReferenceLinks references={references} />
	{/if}
{/if}
