// src/ui/molecules/attributes/transparency/SourceVisibilityDetails.svelte
<script lang="ts">
	// Types/constants
	import type { SourceVisibilityValue } from '@/schema/attributes/transparency/source-visibility'
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'


	// Props
	let {
		wallet,
		value,
	}: {
		wallet: RatedWallet
		value: SourceVisibilityValue
	} = $props()


	// Components
	import Typography from '@/ui/atoms/Typography.svelte'
</script>

<Typography 
	content={{
		contentType: ContentType.MARKDOWN,
		markdown: (
			wallet.metadata.repoUrl === null ?
				'Source code visibility information is not available.'
			:
				`The source code for **{{WALLET_NAME}}** is publicly viewable here.`
		)
	}}
	strings={{ WALLET_NAME: wallet.metadata.displayName }}
/>

{#if wallet.metadata.repoUrl !== null}
	<a 
		href={typeof wallet.metadata.repoUrl === 'string' ? wallet.metadata.repoUrl : wallet.metadata.repoUrl.url}
		target="_blank"
		rel="noopener noreferrer"
		class="repo-link"
	>
		View Source Code
	</a>
{/if}


<style>
	.repo-link {
		margin-top: 0.5rem;
		display: inline-block;
	}
</style>

// src/ui/molecules/attributes/transparency/SourceVisibilityDetails.tsx
import type { RatedWallet } from '@/schema/wallet'
import { Typography } from '@mui/material'
import type React from 'react'
import { ExternalLink } from '../../../atoms/ExternalLink'
import { subsectionWeight } from '@/components/constants'
import type { SourceVisibilityValue } from '@/schema/attributes/transparency/source-visibility'
import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon'

export function SourceVisibilityDetails({
	wallet,
	value,
}: {
	wallet: RatedWallet
	value: SourceVisibilityValue
}): React.JSX.Element {
	if (wallet.metadata.repoUrl === null) {
		return (
			<WrapRatingIcon rating={value.rating}>
				<Typography fontWeight={subsectionWeight}>
					Source code visibility information is not available.
				</Typography>
			</WrapRatingIcon>
		)
	}

	return (
		<WrapRatingIcon rating={value.rating}>
			<Typography fontWeight={subsectionWeight}>
				The source code for <strong>{wallet.metadata.displayName}</strong> is{' '}
				<ExternalLink url={wallet.metadata.repoUrl}>publicly viewable here</ExternalLink>.
			</Typography>
		</WrapRatingIcon>
	)
}
